# Generated by Django 2.1.1 on 2019-09-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0005_auto_20190918_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumelist',
            name='job_fit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='salary_fit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resumelist',
            name='work_year_avg',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
