# Generated by Django 2.1.1 on 2019-09-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruit_company_name', models.CharField(max_length=100)),
                ('recruit_summary', models.CharField(max_length=100)),
                ('recruit_company', models.CharField(max_length=100)),
                ('recruit_position', models.CharField(max_length=100)),
                ('recruit_position2', models.CharField(max_length=100)),
                ('recruit_position_detail', models.CharField(max_length=100)),
                ('recruit_salary', models.CharField(max_length=100)),
                ('recruit_position_detail2', models.TextField()),
                ('recruit_company_detail', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
